import Link from "next/link";
import { ArrowRight, CheckCircle2, MapPinned, MessageSquareHeart, Sparkles, WandSparkles } from "lucide-react";

const features = [
  [MapPinned, "One source of truth", "Update business facts, hours, categories, and URLs across every location."],
  [MessageSquareHeart, "Reviews with judgment", "AI prepares on-brand responses and keeps sensitive feedback in human review."],
  [WandSparkles, "Local content on autopilot", "Create useful, location-specific SEO drafts without the monthly blank page."],
];
export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-zinc-950 text-white"><div className="absolute inset-x-0 top-0 -z-0 h-[560px] bg-[radial-gradient(ellipse_at_top,rgba(79,70,229,.27),transparent_60%)]" />
    <nav className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link href="/" className="text-xl font-semibold tracking-tight">local<span className="text-indigo-400">atlas</span></Link><div className="flex items-center gap-5 text-sm"><Link href="#features" className="hidden text-zinc-300 hover:text-white sm:block">Product</Link><Link href="/login" className="rounded-lg bg-white px-3.5 py-2 font-medium text-zinc-950 hover:bg-zinc-200">Sign in</Link></div></nav>
    <section className="relative z-10 mx-auto max-w-4xl px-6 pb-24 pt-24 text-center sm:pt-32"><div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-400/30 bg-indigo-400/10 px-3 py-1 text-xs font-medium text-indigo-200"><Sparkles className="h-3.5 w-3.5" /> Local presence, under control</div><h1 className="text-balance text-5xl font-semibold tracking-[-.045em] sm:text-7xl">Be accurate everywhere customers look.</h1><p className="mx-auto mt-6 max-w-2xl text-pretty text-lg leading-8 text-zinc-300">The calm control center for multi-location brands. Keep listings accurate, respond thoughtfully, and turn every neighborhood into search visibility.</p><div className="mt-9 flex justify-center gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-lg bg-indigo-500 px-5 py-3 text-sm font-semibold hover:bg-indigo-400">Connect your locations <ArrowRight className="h-4 w-4" /></Link><Link href="#features" className="rounded-lg border border-zinc-700 px-5 py-3 text-sm font-medium text-zinc-200 hover:bg-white/5">Explore platform</Link></div><div className="mt-16 grid grid-cols-3 rounded-xl border border-white/10 bg-white/[.03] p-5 text-left backdrop-blur"><div><p className="text-2xl font-semibold">22+</p><p className="mt-1 text-xs text-zinc-400">directories</p></div><div className="border-x border-white/10 px-5"><p className="text-2xl font-semibold">1</p><p className="mt-1 text-xs text-zinc-400">source of truth</p></div><div className="pl-5"><p className="text-2xl font-semibold">∞</p><p className="mt-1 text-xs text-zinc-400">locations</p></div></div></section>
    <section id="features" className="relative z-10 mx-auto max-w-6xl px-6 pb-24"><div className="grid gap-4 md:grid-cols-3">{features.map(([Icon, title, text]) => <div key={title as string} className="rounded-xl border border-white/10 bg-zinc-900/60 p-6"><Icon className="h-5 w-5 text-indigo-400" /><h2 className="mt-6 font-medium">{title as string}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{text as string}</p></div>)}</div><p className="mt-12 flex justify-center gap-2 text-sm text-zinc-400"><CheckCircle2 className="h-4 w-4 text-emerald-400" /> Built for teams that care about the last mile of local search.</p><footer className="mt-10 border-t border-white/10 pt-6 text-center text-sm text-zinc-400">Questions or need a managed setup? <a className="font-medium text-indigo-300 hover:text-white" href="mailto:hi@11i.co">hi@11i.co</a></footer></section>
  </main>;
}
