export const industries = [
  { slug: "banks-financial-services", name: "Banks & Financial Services", title: "Map listing management for banks and financial services", description: "Keep branch hours, ATM locations, service counters and contact details accurate across the map platforms customers use.", outcomes: ["Consistent branch, ATM and service-centre data", "Change workflows with clear approvals", "Local visibility and reputation reporting"], blogs: ["nap-consistency-guide", "google-business-profile-optimisation", "multi-location-local-seo-reporting"] },
  { slug: "franchises", name: "Franchises", title: "Local SEO and map management for franchises", description: "Give every franchise location accurate local data while maintaining central brand and approval control.", outcomes: ["A single source of truth for every outlet", "Local campaign and review workflows", "Franchise-ready reporting"], blogs: ["local-seo-strategy-for-multi-location-businesses", "local-seo-agency-onboarding", "local-seo-roadmap-90-days"] },
  { slug: "hospitals-healthcare", name: "Hospitals & Healthcare", title: "Healthcare location visibility and patient journey optimisation", description: "Help patients find the correct hospital, clinic, department or service location with dependable public information.", outcomes: ["Accurate hours, phone and location information", "Patient-first local pages and directions", "Careful review-response governance"], blogs: ["location-page-seo-template", "review-response-strategy", "local-seo-photos-and-media"] },
  { slug: "clinics", name: "Clinics & Practices", title: "Local SEO for clinics and multi-site practices", description: "Turn location searches into informed appointment enquiries with clear service, contact and access information.", outcomes: ["Service and location page clarity", "Profile, photo and review workflows", "Conversion paths for calls and bookings"], blogs: ["local-keyword-research-by-service-area", "local-conversion-rate-optimisation", "answer-engine-optimisation-aeo-guide"] },
  { slug: "retail-ecommerce", name: "Retail & Ecommerce", title: "Retail and ecommerce local search optimisation", description: "Connect local store discovery with product, collection and fulfilment information so online demand becomes store visits and qualified orders.", outcomes: ["Store, pickup and service-location accuracy", "Local collection and product discovery content", "Location-level conversion measurement"], blogs: ["local-seo-content-calendar", "local-seo-photos-and-media", "local-conversion-rate-optimisation"] },
  { slug: "automotive", name: "Automotive", title: "Automotive multi-location map management", description: "Make dealership, service-centre and workshop information accurate where vehicle buyers and owners search locally.", outcomes: ["Service-centre and dealership visibility", "Review and local content operations", "Branch-level reporting"], blogs: ["bing-places-listing-management", "local-seo-audit-checklist", "how-to-create-map-listings-for-clients"] },
] as const;
export const industryBySlug = (slug: string) => industries.find((industry) => industry.slug === slug);
